name: Run Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Recreate secret file from base64
        run: |
          mkdir -p upload
          echo "${{ secrets.DOMAIN_SERVER_DETAILS }}" | base64 -d > upload/DomainServer

      - name: Run Playwright tests
        run: |
          LOGIN_FILE=upload/DomainServer
          echo "Running tests with LOGIN_FILE=$LOGIN_FILE"
          # Use environment variables or pass them to the command
          ls -l 
          cat $LOGIN_FILE
        env:
          LOGIN_FILE: upload/DomainServer
